@startuml
'https://plantuml.com/sequence-diagram

autonumber

Job -> Database: Read from database
Job <-- Database: Received records

Job -> Processor: Process the records(Batch processor)
Job <-- Processor: Process completed(Batch processor)
Job -> Kafka: Send to Kafka(Kafka writer)
Consumer -> Kafka: Consume records
@enduml